---
#jinja2 has to evaluate this string seperately, because it is not possible to just include this string in a "when" statement
- set_fact:
    registrar_enabled: "{{ default_settings.registrar.general.enabled if not (ansible_local is defined and ansible_local.registrar is defined and ansible_local.registrar.general is defined) else ansible_local.registrar.general.enabled | default(default_settings.registrar.general.enabled) }}"
