---
- include: ../../common/tasks/other_env.yml 

- name: install services
  apt: name={{ item }} state={{ apt_target_state }} force=yes update_cache=yes cache_valid_time={{ apt_cache_time }} #default_release=jessie
  with_items:
    - privoxy
      
- name: add privoxy user to loggers group
  user: name=privoxy groups="tmp-logger" append=yes
  
- name: enable services
  service: name={{ item }} enabled=yes
  with_items:
    - privoxy

- name: copy privoxy config
  copy: src=privoxy/ dest=/etc/privoxy/
  notify: 
    - restart privoxy
    
- name: copy config file
  template: src=config dest=/etc/privoxy/config 
  notify:
    - restart privoxy

- name: copy custom template files
  synchronize: src={{role_path}}/files/custom_templates/ dest=/etc/privoxy/custom_templates/ delete=yes recursive=yes checksum=yes
  notify:
    - restart privoxy

- name: create privoxy log dir
  file: path={{default_settings.log.general.path}}/{{default_settings.log.privoxy.subdir}} state=directory mode=0755 owner=privoxy

- name: create tmpfiles.d conf file
  template: src=systemd-log-dir dest=/usr/lib/tmpfiles.d/privoxy.conf

- name: modify logdir in privoxy init script
  lineinfile:
    dest: /etc/init.d/privoxy
    regexp: "^LOGDIR="
    line: "LOGDIR={{default_settings.log.general.path}}/{{default_settings.log.privoxy.subdir}}"
  notify: restart privoxy
  register: res

- name: remove default logfiles
  file: path=/var/log/privoxy state=absent
  when: res|changed or default_settings.log.general.path != "/var/log" or default_settings.log.privoxy.subdir != "privoxy"

- name: remove log files from other environment
  file: path={{other_env.default_settings.log.general.path}}/{{other_env.default_settings.log.privoxy.subdir}} state=absent
  when: res|changed

- name: modify logrotate.d entry
  file: path=/etc/logrotate.d/privoxy state=absent
