---
  - include: ../../tor/tasks/tor_state.yml tags=toggle_tor,toggle_silent,configure_devices
  - include_vars: ../../vpn/defaults/main.yml

  - name: install services
    apt: name={{ item }} state={{ apt_target_state }} force=yes update_cache=yes cache_valid_time={{ apt_cache_time }}
    with_items:
     - iptables
     - iptables-persistent

  - name: copy the iptables rules file
    template: src=iptables.upribox.ipv4 dest=/etc/iptables/rules.v4 owner=root group=root mode=0644
    notify:
     - restore iptables
    tags:
     - toggle_tor
     - toggle_silent
     - configure_devices

  - name: copy the iptables rules file
    template: src=iptables.upribox.ipv6 dest=/etc/iptables/rules.v6 owner=root group=root mode=0644
    notify:
     - restore ip6tables
    tags:
     - toggle_tor
     - toggle_silent
     - configure_devices
