---
- include: ../tasks/vpn_state.yml tags=toggle_vpn

- name: restart openvpn
  service: name=openvpn state=stopped

- name: restart openvpn-su
  service: name="openvpn-su" state={{"restarted" if vpn|bool else "stopped"}}
