---
  # we use this to determine if the script is running for the first time -> user pi gets deleted on first run
- name: check if default user exists
  shell: /usr/bin/getent passwd "{{ raspberry_default_user }}" | /usr/bin/wc -l | /usr/bin/tr -d ' '
  register: user_exist
  changed_when: false

- name: set hostname
  hostname: name="{{ hostname }}"

- name: configure locale
  shell: 'update-locale LC_ALL="en_GB.UTF-8" LANG="en_GB.UTF-8"'

- name: create sudo group
  group: name="{{ sudo_group }}" state=present

- name: create remote user
  user: name="{{ remote_user }}" shell="{{ remote_user_login_shell }}" groups="{{sudo_group}}" append=yes

- name: add authorized key
  authorized_key: user="{{ remote_user }}" key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: pull_deployment is not defined

- name: expand disk space
  command: /usr/bin/raspi-config --expand-rootfs

- name: configure sudoers
  template: src=sudoers.j2 dest=/etc/sudoers validate='visudo -cf %s'

- name: rebooting raspberry Pi ...
  remote_user: "{{ remote_user }}"
  shell: /bin/sleep 3 && /sbin/reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for raspberry Pi to restart
  local_action:
    wait_for
    host={{ inventory_hostname }}
    port=22
    delay=30
    timeout=300
  sudo: false

- name: remove default user
  remote_user: "{{ remote_user }}"
  user: name="{{ raspberry_default_user }}" state=absent remove=yes
